FROM node:10.15.0 as react-dev
WORKDIR '/app'
COPY package.json ./
COPY package-lock.json ./
RUN npm install
RUN npm install --save jspdf-react
RUN npm audit fix
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
