FROM node:10.15.0 as react-production
ARG  URL_API_EMPLOYEE
ARG URL_API
ARG URL_API_FACULTY
ARG URL_API_FORM
ARG URL_API_PROCESS
ARG URL_API_USER
WORKDIR '/app'
COPY package.json ./
COPY package-lock.json ./
RUN npm install
RUN npm install --save jspdf-react
RUN npm audit fix
RUN npm install -g serve
COPY . .
RUN REACT_APP_URL_API_EMPLOYEE=$URL_API_EMPLOYEE REACT_APP_URL_API=$URL_API REACT_APP_URL_API_FACULTY=$URL_API_FACULTY REACT_APP_URL_API_FORM=$URL_API_FORM REACT_APP_URL_API_PROCESS=$URL_API_PROCESS REACT_APP_URL_API_USER=$URL_API_USER npm run build --production
EXPOSE 5000
CMD ["serve", "-s", "build"]
